const genres = 
[
    {"id":28,"name":"Action"},
    {"id":12,"name":"Adventure"},
    {"id":16,"name":"Animation"},
    {"id":35,"name":"Comedy"},
    {"id":80,"name":"Crime"},
    {"id":99,"name":"Documentary"},
    {"id":18,"name":"Drama"},
    {"id":10751,"name":"Family"},
    {"id":14,"name":"Fantasy"},
    {"id":36,"name":"History"},
    {"id":27,"name":"Horror"},
    {"id":10402,"name":"Music"},
    {"id":9648,"name":"Mystery"},
    {"id":10749,"name":"Romance"},
    {"id":878,"name":"Science Fiction"},
    {"id":10770,"name":"TV Movie"},
    {"id":53,"name":"Thriller"},
    {"id":10752,"name":"War"},
    {"id":37,"name":"Western"}
]

const movies = 
[{
    "adult":false,
    "backdrop_path":"/ugS5FVfCI3RV0ZwZtBV3HAV75OX.jpg",
    "genre_ids":[16,878,28],
    "id":610150,
    "original_language":"ja",
    "original_title":"ドラゴンボール超 スーパーヒーロー",
    "overview":"The Red Ribbon Army, an evil organization that was once destroyed by Goku in the past, has been reformed by a group of people who have created new and mightier Androids, Gamma 1 and Gamma 2, and seek vengeance against Goku and his family.",
    "popularity":8934.503,
    "poster_path":"/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg",
    "release_date":"2022-06-11",
    "title":"Dragon Ball Super: Super Hero",
    "video":false,
    "vote_average":7.5,
    "vote_count":126
},{
    "adult":false,
    "backdrop_path":"/AfvIjhDu9p64jKcmohS4hsPG95Q.jpg",
    "genre_ids":[27,53],
    "id":756999,
    "original_language":"en",
    "original_title":"The Black Phone",
    "overview":"Finney Blake, a shy but clever 13-year-old boy, is abducted by a sadistic killer and trapped in a soundproof basement where screaming is of little use. When a disconnected phone on the wall begins to ring, Finney discovers that he can hear the voices of the killer’s previous victims. And they are dead set on making sure that what happened to them doesn’t happen to Finney.",
    "popularity":2856.716,
    "poster_path":"/lr11mCT85T1JanlgjMuhs9nMht4.jpg",
    "release_date":"2022-06-22",
    "title":"The Black Phone",
    "video":false,
    "vote_average":8,"vote_count":2047
},{
    "adult":false,
    "backdrop_path":"/68GfuBjPr1wLLctLIqxgXl2N0GJ.jpg",
    "genre_ids":[28,12,878],
    "id":634649,"original_language":"en",
    "original_title":"Spider-Man: No Way Home",
    "overview":"Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    "popularity":1514.09,
    "poster_path":"/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    "release_date":"2021-12-15",
    "title":"Spider-Man: No Way Home",
    "video":false,
    "vote_average":8,
    "vote_count":14771
},{
    "adult":false,
    "backdrop_path":"/ftGzl2GCyko61Qp161bQElN2Uzd.jpg",
    "genre_ids":[28,53],
    "id":961484,
    "original_language":"en",
    "original_title":"Last Seen Alive",
    "overview":"After Will Spann's wife suddenly vanishes at a gas station, his desperate search to find her leads him down a dark path that forces him to run from authorities and take the law into his own hands.",
    "popularity":1136.243,
    "poster_path":"/qvqyDj34Uivokf4qIvK4bH0m0qF.jpg",
    "release_date":"2022-05-19",
    "title":"Last Seen Alive",
    "video":false,
    "vote_average":6.6,
    "vote_count":255
},{
    "adult":false,
    "backdrop_path":"/4dNv1W1KMSLdYGz0tCEaynF0E4Q.jpg",
    "genre_ids":[28,53,80],
    "id":854467,
    "original_language":"en",
    "original_title":"Indemnity",
    "overview":"An ex-fireman with PTSD goes on the run when accused of a crime he doesn't even remember committing, leading him down a rabbit hole of conspiracy to the highest degree.",
    "popularity":1010.238,
    "poster_path":"/tVbO8EAbegVtVkrl8wNhzoxS84N.jpg",
    "release_date":"2022-02-11",
    "title":"Indemnity",
    "video":false,
    "vote_average":7.1,
    "vote_count":56
},{
    "adult":false,
    "backdrop_path":"/k2G4WqGiT60K9yJnPh4K6VLnl3A.jpg",
    "genre_ids":[28,12,14],
    "id":639933,
    "original_language":"en",
    "original_title":"The Northman",
    "overview":"Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy's mother. Two decades later, Amleth is now a Viking who's on a mission to save his mother, kill his uncle and avenge his father.",
    "popularity":966.489,
    "poster_path":"/8p9zXB7M78nZpm215zHfqpknMeM.jpg",
    "release_date":"2022-04-07",
    "title":"The Northman",
    "video":false,
    "vote_average":7.2,
    "vote_count":2207
},{
    "adult":false,
    "backdrop_path":"/C8FpZfTPEZDjngPlatiFsaDB4A.jpg",
    "genre_ids":[28,35,80],
    "id":718930,
    "original_language":"en",
    "original_title":"Bullet Train",
    "overview":"Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug's latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world's fastest train.",
    "popularity":923.663,
    "poster_path":"/nF1a7P9lUq9kNas9RIvSEQ412qN.jpg",
    "release_date":"2022-07-03",
    "title":"Bullet Train",
    "video":false,
    "vote_average":7.5,
    "vote_count":426
},{
    "adult":false,
    "backdrop_path":"/ft1jH9Zrjx48obILr8NpgfvLYku.jpg",
    "genre_ids":[27,53],
    "id":760161,
    "original_language":"en",
    "original_title":"Orphan: First Kill",
    "overview":"After escaping from an Estonian psychiatric facility, Leena Klammer travels to America by impersonating Esther, the missing daughter of a wealthy family. But when her mask starts to slip, she is put against a mother who will protect her family from the murderous “child” at any cost.",
    "popularity":801.289,
    "poster_path":"/cQYfh1jWzeizgJI2Z66y9h8YKTU.jpg",
    "release_date":"2022-07-27",
    "title":"Orphan: First Kill",
    "video":false,
    "vote_average":7.2,
    "vote_count":209
},{
    "adult":false,
    "backdrop_path":"/8TUb2U9GN3PonbXAQ1FBcJ4XeXu.jpg",
    "genre_ids":[27,53],
    "id":760741,
    "original_language":"en",
    "original_title":"Beast",
    "overview":"A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.",
    "popularity":765.05,
    "poster_path":"/xIGr7UHsKf0URWmyyd5qFMAq4d8.jpg",
    "release_date":"2022-08-11",
    "title":"Beast",
    "video":false,
    "vote_average":6.8,
    "vote_count":34
},{
    "adult":false,
    "backdrop_path":"/sS4MadD7pKMt251vKxdJo2YrkYP.jpg",
    "genre_ids":[10749,18],
    "id":744276,
    "original_language":"en",
    "original_title":"After Ever Happy",
    "overview":"As a shocking truth about a couple's families emerges, the two lovers discover they are not so different from each other. Tessa is no longer the sweet, simple, good girl she was when she met Hardin — any more than he is the cruel, moody boy she fell so hard for.",
    "popularity":548.054,
    "poster_path":"/moogpu8rNkEjTgFyLXwhPghft5w.jpg",
    "release_date":"2022-08-24",
    "title":"After Ever Happy",
    "video":false,
    "vote_average":6.3,
    "vote_count":6
},{
    "adult":false,
    "backdrop_path":"/54PmeEzQMvpojpJBku61ZGQnWUX.jpg",
    "genre_ids":[16,12,28,14],
    "id":900667,
    "original_language":"ja",
    "original_title":"ONE PIECE FILM RED",
    "overview":"Uta — the most beloved singer in the world. Her voice, which she sings with while concealing her true identity, has been described as “otherworldly.” She will appear in public for the first time at a live concert. As the venue fills with all kinds of Uta fans — excited pirates, the Navy watching closely, and the Straw Hats led by Luffy who simply came to enjoy her sonorous performance — the voice that the whole world has been waiting for is about to resound. The story begins with the shocking fact that she is \"Shanks' daughter.”",
    "popularity":469.033,
    "poster_path":"/wDed9MJgcRNs34ncGuegjr7ik42.jpg",
    "release_date":"2022-08-06",
    "title":"One Piece Film: Red",
    "video":false,
    "vote_average":7.7,
    "vote_count":63
},{
    "adult":false,
    "backdrop_path":"/7ef3yg5eCE6ZGKMsqUrfH8KdSMA.jpg",
    "genre_ids":[16,28,10751,878,35],
    "id":539681,
    "original_language":"en",
    "original_title":"DC League of Super-Pets",
    "overview":"When Superman and the rest of the Justice League are kidnapped, Krypto the Super-Dog must convince a rag-tag shelter pack - Ace the hound, PB the potbellied pig, Merton the turtle and Chip the squirrel - to master their own newfound powers and help him rescue the superheroes.",
    "popularity":439.226,
    "poster_path":"/c7cTXzECmMCqFeae7B0klff6UDR.jpg",
    "release_date":"2022-07-27",
    "title":"DC League of Super-Pets",
    "video":false,"vote_average":7.1,"vote_count":99
},{
    "adult":false,
    "backdrop_path":"/xVbppM1xgbskOKgOuV8fbWBWHtt.jpg",
    "genre_ids":[27,9648,878,53],
    "id":762504,
    "original_language":"en",
    "original_title":"Nope",
    "overview":"Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery.",
    "popularity":424.276,
    "poster_path":"/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg",
    "release_date":"2022-07-20",
    "title":"Nope",
    "video":false,
    "vote_average":7,
    "vote_count":425
},{
    "adult":false,
    "backdrop_path":"/A5OlbPn10H3E16CY8CT8fplWZy7.jpg",
    "genre_ids":[80,18,53],
    "id":689700,
    "original_language":"en",
    "original_title":"Clean",
    "overview":"Tormented by a past life, garbage man Clean attempts a life of quiet redemption. But when his good intentions mark him a target of a local crime boss, Clean is forced to reconcile with the violence of his past.",
    "popularity":373.197,
    "poster_path":"/kRpKJstAW7DsoPAEBW2Kk1uD9Q6.jpg",
    "release_date":"2022-01-28","title":"Clean",
    "video":false,
    "vote_average":6.5,
    "vote_count":201
},{
    "adult":false,
    "backdrop_path":"/iDeWAGnmloZ5Oz3bocDp4rSbUXd.jpg",
    "genre_ids":[28,53],
    "id":823625,
    "original_language":"en",
    "original_title":"Blacklight",
    "overview":"Travis Block is a shadowy Government agent who specializes in removing operatives whose covers have been exposed. He then has to uncover a deadly conspiracy within his own ranks that reaches the highest echelons of power.",
    "popularity":353.095,
    "poster_path":"/bv9dy8mnwftdY2j6gG39gCfSFpV.jpg",
    "release_date":"2022-02-10",
    "title":"Blacklight",
    "video":false,
    "vote_average":6.3,
    "vote_count":578
},{
    "adult":false,
    "backdrop_path":"/kpM7wX8K66bGZkYvfHXIrnXvDRS.jpg",
    "genre_ids":[80,28],
    "id":619803,
    "original_language":"ko",
    "original_title":"범죄도시 2",
    "overview":"The ‘Beast Cop’ Ma Seok-do heads to a foreign country to extradite a suspect, but soon after his arrival, he discovers additional murder cases and hears about a vicious killer who has been committing crimes against tourists for several years.",
    "popularity":216.147,
    "poster_path":"/tqHXCshqysM6DPnXeFIR74fNdKw.jpg",
    "release_date":"2022-05-18",
    "title":"The Roundup",
    "video":false,
    "vote_average":7.3,
    "vote_count":53
},{
    "adult":false,
    "backdrop_path":"/wp3vpSWAIjKSEeYb8F5NSZfONqw.jpg",
    "genre_ids":[28,12,878],
    "id":545611,
    "original_language":"en",
    "original_title":"Everything Everywhere All at Once",
    "overview":"An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.","popularity":214.232,
    "poster_path":"/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    "release_date":"2022-03-24",
    "title":"Everything Everywhere All at Once",
    "video":false,
    "vote_average":8.3,
    "vote_count":1378
},{
    "adult":false,
    "backdrop_path":"/n4Iy2cE52WsTKeNtuSD7vgu2qwf.jpg",
    "genre_ids":[53],
    "id":985939,
    "original_language":"en",
    "original_title":"Fall",
    "overview":"For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights.","popularity":168.672,"poster_path":"/v28T5F1IygM8vXWZIycfNEm3xcL.jpg","release_date":"2022-08-11","title":"Fall","video":false,"vote_average":7.2,"vote_count":12},{"adult":false,"backdrop_path":"/mDvx0cafHm1Z0R295wMxzpVTGf9.jpg","genre_ids":[12,16,35,10751,14],"id":676705,"original_language":"fr","original_title":"Pil","overview":"Pil, a little vagabond girl, lives on the streets of the medieval city of Roc-en-Brume, along with her three tame weasels. She survives of food stolen from the castle of the sinister Regent Tristain. One day, to escape his guards, Pil disguises herself as a princess. Thus she embarks upon a mad, delirious adventure, together with Crobar, a big clumsy guard who thinks she's a noble, and Rigolin, a young crackpot jester. Pil is going to have to save Roland, rightful heir to the throne under the curse of a spell. This adventure will turn the entire kingdom upside down, and teach Pil that nobility can be found in all of us.","popularity":204.771,"poster_path":"/abPQVYyNfVuGoFUfGVhlNecu0QG.jpg","release_date":"2021-08-11","title":"Pil's Adventures","video":false,"vote_average":6.7,"vote_count":112},{"adult":false,"backdrop_path":"/4nswAImPQjLbyCpXkwHjFlXxAeG.jpg","genre_ids":[16,18,878],"id":741335,"original_language":"ja","original_title":"アイの歌声を聴かせて","overview":"Satomi is fine being alone until an AI named Shion joins her class with a song and a promise to make her happy. While Shion’s musical numbers and princess gowns don’t quite pass as human, her antics bring Satomi closer to four other classmates. Together, they make memories worth saving, but even our most precious data can be erased.",
    "popularity":192.862,
    "poster_path":"/bDx77d1SLXGWIGMlz6nWx0SghiT.jpg",
    "release_date":"2021-10-29",
    "title":"Sing a Bit of Harmony",
    "video":false,
    "vote_average":8,
    "vote_count":9
}]